spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/diploma?currentSchema=car_rent
    username: postgres
    password: TG456456tg
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

